---
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: sentry-studio
    namespace: dolittle
  spec:
    template:
      metadata:
        labels:
          app: sentry
          name: sentry
      spec:
        containers:
        - name: sentry-backend
          image: dolittle/sentry-studio-backend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
        - name: sentry-frontend
          image: dolittle/sentry-studio-backend
          imagePullPolicy: Always
          ports:
          - containerPort: 80
